"""
Stage 3c/d: Generate layer3_ranked_advice.md from rankings.json.

The honest framing paragraph and per-stock rationale cards are injected
by Claude (LLM steps) before this script writes the final structure.
This script assembles the template and the methodology section.
"""

import json
import argparse
from pathlib import Path


_DISCLAIMER = Path("/home/claude/financial-research-skill-v0.2/assets/disclaimer.md")

_METHODOLOGY = """## Methodology disclosure

- **Universe**: HKMA-approved global funds distributed through HK private banking channels
- **Filter**: US-listed equities only (ADRs included; non-US primary listings excluded)
- **Quality screen**: ROE persistence (>= 3 positive years in 5), debt sanity (D/E < 5.0), earnings continuity (no 3 consecutive negative NI years), minimum data availability (>= 2 of 3 key metrics at confidence >= 0.4)
- **Ranking signal**: 50% fundamental quality (ROE 5y avg percentile rank) + 50% consensus-with-crowding-discount
- **Provider routing**: EDGAR (confidence 0.9) → yfinance fallback (confidence 0.5)
- **Sample size**: {n_funds} HKMA-approved funds — this is a small sample; results are NOT statistically significant

## Important caveats

- Sample size of {n_funds} funds is small; rankings are not statistically significant
- Top-N disclosure in fund prospectuses introduces 30–60 day staleness
- HK distribution-channel bias is not corrected; rankings reflect that bias, not the global equity market
- This is a filter and ranking tool, not an alpha-generation or portfolio construction tool
"""

_CARD_TEMPLATE = """### #{rank}   {ticker}   {name}

**Held by:** {n_funds_holding} of {total_funds} funds ({pct:.0%}){crowding_flag}

**Avg weight where held:** {avg_weight:.2%}  |  **Max weight:** {max_weight:.2%}  |  **asof:** {asof}

**Quality screen:** PASS  |  **Confidence:** {confidence}
- ROE 5y avg: {roe_avg}
- EV/EBITDA: {ev_ebitda}
- Debt/Equity: {de}

**Composite rank:** {rank} of {n_passed}   |   **Tier:** {tier}{adr_note}

**Rank rationale:**
{rationale}

**Bias note:** This rank reflects HK distribution channel preference. It is not a market-wide alpha signal.
"""

_CROWDING_FLAG = (
    "\n\n> ⚠ HIGH CROWDING — multiple funds hold large positions; "
    "vulnerable to coordinated unwind."
)


def fmt_metric(val, fmt=".2f", suffix="") -> str:
    if val is None:
        return "n/a"
    return f"{val:{fmt}}{suffix}"


def build_layer3_md(
    rankings: dict,
    n_funds: int,
    honest_framing: str,
    rationale_cards: dict[str, str],
) -> str:
    ranked = rankings.get("ranked", [])
    n_passed = rankings.get("n_passed_universe", len(ranked))

    lines = ["# Layer 3: Ranked Watchlist", ""]

    lines += ["## What this analysis is and is not", ""]
    lines += [honest_framing, ""]

    # Tier sections
    for tier_name in ("A", "B", "C"):
        tier_stocks = [s for s in ranked if s.get("tier") == tier_name]
        if not tier_stocks:
            continue
        lines += [f"## Tier {tier_name}", ""]
        for s in tier_stocks:
            tkr = s["ticker"]
            crowding_flag = _CROWDING_FLAG if s.get("is_high_crowding") else ""
            adr_note = "\n\n> ADR — fundamentals sourced from 20-F or yfinance fallback." \
                if s.get("is_adr") else ""
            card = _CARD_TEMPLATE.format(
                rank=s["rank"],
                ticker=tkr,
                name=s.get("name") or "",
                n_funds_holding=s.get("n_funds_holding", 0),
                total_funds=n_funds,
                pct=(s.get("n_funds_holding", 0) / max(n_funds, 1)),
                crowding_flag=crowding_flag,
                avg_weight=s.get("avg_weight", 0),
                max_weight=s.get("max_weight", 0),
                asof="",
                confidence=fmt_metric(s.get("data_confidence")),
                roe_avg=fmt_metric(s.get("roe_5y_avg"), ".1%") if s.get("roe_5y_avg") else "n/a",
                ev_ebitda=fmt_metric(s.get("ev_ebitda")),
                de=fmt_metric(s.get("debt_equity")),
                n_passed=n_passed,
                tier=s["tier"],
                adr_note=adr_note,
                rationale=rationale_cards.get(tkr, "_Rationale generated by Claude in Step 3b._"),
            )
            lines += [card, ""]

    lines += [_METHODOLOGY.format(n_funds=n_funds)]

    # Disclaimer
    try:
        disc = _DISCLAIMER.read_text(encoding="utf-8")
    except Exception:
        disc = "_See assets/disclaimer.md_"
    lines += ["## Disclaimer", "", disc]

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--rankings", required=True)
    ap.add_argument("--n-funds", type=int, required=True)
    ap.add_argument("--framing", required=True, help="Path to honest_framing.txt written by Claude")
    ap.add_argument("--rationale-dir", help="Directory with per-ticker rationale .txt files")
    ap.add_argument("--out", default="/home/claude/work/layer3_ranked_advice.md")
    args = ap.parse_args()

    rankings = json.loads(Path(args.rankings).read_text(encoding="utf-8"))
    honest_framing = Path(args.framing).read_text(encoding="utf-8")

    rationale_cards: dict[str, str] = {}
    if args.rationale_dir:
        for f in Path(args.rationale_dir).glob("*.txt"):
            rationale_cards[f.stem.upper()] = f.read_text(encoding="utf-8").strip()

    md = build_layer3_md(rankings, args.n_funds, honest_framing, rationale_cards)

    Path(args.out).parent.mkdir(parents=True, exist_ok=True)
    Path(args.out).write_text(md, encoding="utf-8")
    print(f"Layer 3 report written to {args.out}")


if __name__ == "__main__":
    main()
